name: admob_flutter_example
description: Demonstrates how to use the admob_flutter plugin.
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  admob_flutter:
    path: ../
  cupertino_icons: ^1.0.2
  firebase_analytics: ^9.0.4
  firebase_core: ^1.10.6
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: 1.11.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
